@startuml
start
:User executes delete command;

if () then ([No INDEX provided])
    :Show invalid command format as error message;

else ([else])
    if () then ([INDEX provided is invalid])
    :Show invalid command format as error message;
    else([else])
    : Deletes the specific student from the contact list;
    : Displays updated student list in the GUI;
    endif

endif
stop
@enduml
