@startuml

start
:User executes filter command;

if () then ([GROUP_NAME KEYWORD parameter is invalid or not provided])
    :Show invalid command format as error message;
    else([else])
    :Displays the filtered student contacts in the result display;
endif
stop

@enduml
