@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MailTelegramCommandParser" as MailTelegramCommandParser LOGIC_COLOR
participant "d:MailTelegramCommand" as MailTelegramCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mailtg g/TUT05")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mailtg g/TUT05")
activate AddressBookParser

create MailTelegramCommandParser
AddressBookParser -> MailTelegramCommandParser
activate MailTelegramCommandParser

MailTelegramCommandParser --> AddressBookParser
deactivate MailTelegramCommandParser

AddressBookParser -> MailTelegramCommandParser : parse("g/TUT05")
activate MailTelegramCommandParser

create MailTelegramCommand
MailTelegramCommandParser -> MailTelegramCommand
activate MailTelegramCommand

MailTelegramCommand --> MailTelegramCommandParser : d
deactivate MailTelegramCommand

MailTelegramCommandParser --> AddressBookParser : d
deactivate MailTelegramCommandParser

MailTelegramCommandParser -[hidden]-> AddressBookParser
destroy MailTelegramCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> MailTelegramCommand : execute()
activate MailTelegramCommand

MailTelegramCommand -> Model : getAddressBook()
activate Model

Model --> MailTelegramCommand
deactivate Model

create CommandResult
MailTelegramCommand -> CommandResult
activate CommandResult

CommandResult --> MailTelegramCommand : result
deactivate CommandResult

MailTelegramCommand --> LogicManager : result
deactivate MailTelegramCommand

[<--LogicManager
deactivate LogicManager
@enduml
