@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkAttendanceCommandParser" as MarkAttendanceCommandParser LOGIC_COLOR
participant "d:MarkAttendanceCommand" as MarkAttendanceCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mail TUT05")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mark 1 g/TUT04 w/1 a/P")
activate AddressBookParser

create MarkAttendanceCommandParser
AddressBookParser -> MarkAttendanceCommandParser
activate MarkAttendanceCommandParser

MarkAttendanceCommandParser --> AddressBookParser
deactivate MarkAttendanceCommandParser

AddressBookParser -> MarkAttendanceCommandParser : parse("TUT05, 1, P")
activate MarkAttendanceCommandParser

create MarkAttendanceCommand
MarkAttendanceCommandParser -> MarkAttendanceCommand
activate MarkAttendanceCommand

MarkAttendanceCommand --> MarkAttendanceCommandParser : d
deactivate MarkAttendanceCommand

MarkAttendanceCommandParser --> AddressBookParser : d
deactivate MarkAttendanceCommandParser

MarkAttendanceCommandParser -[hidden]-> AddressBookParser
destroy MarkAttendanceCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> MarkAttendanceCommand : execute()
activate MarkAttendanceCommand

MarkAttendanceCommand -> Model : getAddressBook()
activate Model

Model --> MarkAttendanceCommand
deactivate Model

create CommandResult
MarkAttendanceCommand -> CommandResult
activate CommandResult

CommandResult --> MarkAttendanceCommand : result
deactivate CommandResult

MarkAttendanceCommand --> LogicManager : result
deactivate MarkAttendanceCommand

[<--LogicManager
deactivate LogicManager
@enduml
